-- TeleTrade Hub PostgreSQL/Supabase schema
-- Generated for migration from MySQL

BEGIN;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id VARCHAR(100),
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  name_de VARCHAR(255),
  name_sk VARCHAR(255),
  name_fr VARCHAR(255),
  name_es VARCHAR(255),
  name_ru VARCHAR(255),
  name_it VARCHAR(255),
  name_tr VARCHAR(255),
  name_ro VARCHAR(255),
  name_pl VARCHAR(255),
  slug VARCHAR(255) NOT NULL UNIQUE,
  parent_id BIGINT,
  description TEXT,
  image_url VARCHAR(500),
  sort_order INTEGER DEFAULT 0,
  is_active SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_is_active ON categories(is_active);

CREATE TABLE IF NOT EXISTS brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id VARCHAR(100),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  logo_url VARCHAR(500),
  description TEXT,
  description_en TEXT,
  description_de TEXT,
  description_sk TEXT,
  description_fr TEXT,
  description_es TEXT,
  description_ru TEXT,
  description_it TEXT,
  description_tr TEXT,
  description_ro TEXT,
  description_pl TEXT,
  website VARCHAR(500),
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_brands_is_active ON brands(is_active);

CREATE TABLE IF NOT EXISTS warranties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  duration_months INTEGER,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_source VARCHAR(20) DEFAULT 'vendor',
  vendor_article_id VARCHAR(100) UNIQUE,
  sku VARCHAR(100) NOT NULL UNIQUE,
  ean VARCHAR(50),
  name VARCHAR(500) NOT NULL,
  name_en VARCHAR(500),
  name_de VARCHAR(500),
  name_sk VARCHAR(500),
  name_fr VARCHAR(500),
  name_es VARCHAR(500),
  name_ru VARCHAR(500),
  name_it VARCHAR(500),
  name_tr VARCHAR(500),
  name_ro VARCHAR(500),
  name_pl VARCHAR(500),
  description TEXT,
  description_en TEXT,
  description_de TEXT,
  description_sk TEXT,
  description_fr TEXT,
  description_es TEXT,
  description_ru TEXT,
  description_it TEXT,
  description_tr TEXT,
  description_ro TEXT,
  description_pl TEXT,
  category_id BIGINT,
  brand_id BIGINT,
  warranty_id BIGINT,
  base_price NUMERIC(10, 2) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'EUR',
  stock_quantity INTEGER DEFAULT 0,
  available_quantity INTEGER DEFAULT 0,
  reserved_quantity INTEGER DEFAULT 0,
  reorder_point INTEGER DEFAULT 0,
  warehouse_location VARCHAR(100),
  is_available SMALLINT DEFAULT 1,
  is_featured SMALLINT DEFAULT 0,
  weight NUMERIC(8, 2),
  dimensions VARCHAR(100),
  color VARCHAR(100),
  storage VARCHAR(50),
  ram VARCHAR(50),
  specifications JSONB,
  meta_title VARCHAR(255),
  meta_description TEXT,
  slug VARCHAR(500) NOT NULL UNIQUE,
  last_synced_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_products_source CHECK (product_source IN ('vendor', 'own'))
);

CREATE INDEX IF NOT EXISTS idx_products_product_source ON products(product_source);
CREATE INDEX IF NOT EXISTS idx_products_ean ON products(ean);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_warranty_id ON products(warranty_id);
CREATE INDEX IF NOT EXISTS idx_products_is_available ON products(is_available);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON products(is_featured);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_products_stock_quantity ON products(stock_quantity);
CREATE INDEX IF NOT EXISTS idx_products_source_available ON products(product_source, is_available);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255),
  sort_order INTEGER DEFAULT 0,
  is_primary SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_is_primary ON product_images(is_primary);

CREATE TABLE IF NOT EXISTS pricing_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type VARCHAR(20) NOT NULL,
  account_type VARCHAR(20) NOT NULL DEFAULT 'customer',
  entity_id BIGINT,
  markup_type VARCHAR(20) DEFAULT 'percentage',
  markup_value NUMERIC(10, 2) NOT NULL,
  priority INTEGER DEFAULT 0,
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_pricing_rule_type CHECK (rule_type IN ('global', 'category', 'brand', 'product')),
  CONSTRAINT chk_pricing_account_type CHECK (account_type IN ('customer', 'merchant')),
  CONSTRAINT chk_pricing_markup_type CHECK (markup_type IN ('percentage', 'fixed'))
);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_rule_type ON pricing_rules(rule_type, entity_id, account_type);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_is_active ON pricing_rules(is_active);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_type VARCHAR(20) NOT NULL DEFAULT 'customer',
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  postal_code VARCHAR(20),
  city VARCHAR(100),
  country VARCHAR(100),
  phone VARCHAR(50),
  mobile VARCHAR(50),
  tax_number VARCHAR(100),
  vat_number VARCHAR(100),
  delivery_address VARCHAR(255),
  delivery_postal_code VARCHAR(20),
  delivery_city VARCHAR(100),
  delivery_country VARCHAR(100),
  account_holder VARCHAR(200),
  bank_name VARCHAR(200),
  iban VARCHAR(50),
  bic VARCHAR(30),
  id_card_file VARCHAR(500),
  passport_file VARCHAR(500),
  business_registration_certificate_file VARCHAR(500),
  vat_certificate_file VARCHAR(500),
  tax_number_certificate_file VARCHAR(500),
  is_active SMALLINT DEFAULT 1,
  email_verified_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_users_account_type CHECK (account_type IN ('customer', 'merchant')),
  CONSTRAINT uq_users_phone UNIQUE (phone)
);

CREATE INDEX IF NOT EXISTS idx_users_account_type ON users(account_type);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(200) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin',
  is_active SMALLINT DEFAULT 1,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_admin_role CHECK (role IN ('super_admin', 'admin', 'manager'))
);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  ip_address VARCHAR(45),
  user_agent VARCHAR(500),
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin_user_id ON admin_sessions(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires_at ON admin_sessions(expires_at);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  ip_address VARCHAR(45),
  user_agent VARCHAR(500),
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_sessions_user_id UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);

CREATE TABLE IF NOT EXISTS addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  label VARCHAR(100),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  company VARCHAR(200),
  street VARCHAR(255) NOT NULL,
  street2 VARCHAR(255),
  address_line1 VARCHAR(255),
  address_line2 VARCHAR(255),
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100),
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(100) NOT NULL,
  phone VARCHAR(50),
  is_default SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) NOT NULL UNIQUE,
  user_id BIGINT,
  guest_email VARCHAR(255),
  status VARCHAR(30) DEFAULT 'pending',
  payment_status VARCHAR(20) DEFAULT 'unpaid',
  fulfillment_status VARCHAR(30) DEFAULT 'pending',
  payment_method VARCHAR(50),
  payment_transaction_id VARCHAR(255),
  subtotal NUMERIC(10, 2) NOT NULL,
  tax NUMERIC(10, 2) DEFAULT 0.00,
  shipping_cost NUMERIC(10, 2) DEFAULT 0.00,
  total NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'EUR',
  billing_address_id BIGINT,
  shipping_address_id BIGINT,
  notes TEXT,
  admin_notes TEXT,
  ip_address VARCHAR(45),
  user_agent VARCHAR(500),
  paid_at TIMESTAMP,
  vendor_order_created_at TIMESTAMP,
  vendor_order_id VARCHAR(100),
  own_items_fulfilled_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'payment_pending', 'paid', 'processing', 'reserved', 'vendor_ordered', 'shipped', 'delivered', 'cancelled', 'refunded')),
  CONSTRAINT chk_orders_payment_status CHECK (payment_status IN ('unpaid', 'pending', 'paid', 'failed', 'refunded')),
  CONSTRAINT chk_orders_fulfillment_status CHECK (fulfillment_status IN ('pending', 'vendor_pending', 'own_fulfilled', 'vendor_fulfilled', 'fulfilled', 'partially_fulfilled'))
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_fulfillment_status ON orders(fulfillment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name VARCHAR(500) NOT NULL,
  product_sku VARCHAR(100) NOT NULL,
  product_source VARCHAR(20) DEFAULT 'vendor',
  vendor_article_id VARCHAR(100),
  quantity INTEGER NOT NULL,
  base_price NUMERIC(10, 2) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  subtotal NUMERIC(10, 2) NOT NULL,
  fulfillment_status VARCHAR(30) DEFAULT 'pending',
  reserved_at TIMESTAMP,
  stock_deducted_at TIMESTAMP,
  shipped_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_order_items_source CHECK (product_source IN ('vendor', 'own')),
  CONSTRAINT chk_order_items_fulfillment_status CHECK (fulfillment_status IN ('pending', 'reserved', 'stock_deducted', 'vendor_ordered', 'shipped', 'fulfilled'))
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_source ON order_items(product_source);
CREATE INDEX IF NOT EXISTS idx_order_items_fulfillment_status ON order_items(fulfillment_status);

CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  vendor_article_id VARCHAR(100) NOT NULL,
  quantity INTEGER NOT NULL,
  vendor_reservation_id VARCHAR(100),
  status VARCHAR(20) DEFAULT 'pending',
  reserved_at TIMESTAMP,
  unreserved_at TIMESTAMP,
  ordered_at TIMESTAMP,
  vendor_response JSONB,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_reservations_status CHECK (status IN ('pending', 'reserved', 'unreserved', 'failed', 'ordered'))
);

CREATE INDEX IF NOT EXISTS idx_reservations_order_id ON reservations(order_id);
CREATE INDEX IF NOT EXISTS idx_reservations_product_id ON reservations(product_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status);
CREATE INDEX IF NOT EXISTS idx_reservations_reserved_at ON reservations(reserved_at);
CREATE INDEX IF NOT EXISTS idx_reservations_vendor_reservation_id ON reservations(vendor_reservation_id);

CREATE TABLE IF NOT EXISTS vendor_sync_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_type VARCHAR(20) DEFAULT 'full',
  status VARCHAR(20) DEFAULT 'started',
  products_synced INTEGER DEFAULT 0,
  products_added INTEGER DEFAULT 0,
  products_updated INTEGER DEFAULT 0,
  products_disabled INTEGER DEFAULT 0,
  error_message TEXT,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP,
  duration_seconds INTEGER,
  CONSTRAINT chk_vendor_sync_type CHECK (sync_type IN ('full', 'incremental')),
  CONSTRAINT chk_vendor_sync_status CHECK (status IN ('started', 'in_progress', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_vendor_sync_log_status ON vendor_sync_log(status);
CREATE INDEX IF NOT EXISTS idx_vendor_sync_log_started_at ON vendor_sync_log(started_at);

CREATE TABLE IF NOT EXISTS vendor_api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint VARCHAR(255) NOT NULL,
  method VARCHAR(10) NOT NULL,
  request_payload JSONB,
  response_payload JSONB,
  status_code INTEGER,
  duration_ms INTEGER,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vendor_api_logs_endpoint ON vendor_api_logs(endpoint);
CREATE INDEX IF NOT EXISTS idx_vendor_api_logs_created_at ON vendor_api_logs(created_at);

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key VARCHAR(100) NOT NULL UNIQUE,
  value TEXT,
  type VARCHAR(20) DEFAULT 'string',
  description VARCHAR(500),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_settings_type CHECK (type IN ('string', 'integer', 'boolean', 'json'))
);

CREATE TABLE IF NOT EXISTS languages (
  id BIGINT PRIMARY KEY,
  code VARCHAR(2) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  is_active SMALLINT DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE categories
  ADD CONSTRAINT fk_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL;

ALTER TABLE products
  ADD CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_products_brand_id FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_products_warranty_id FOREIGN KEY (warranty_id) REFERENCES warranties(id) ON DELETE SET NULL;

ALTER TABLE product_images
  ADD CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE admin_sessions
  ADD CONSTRAINT fk_admin_sessions_admin_user_id FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE;

ALTER TABLE user_sessions
  ADD CONSTRAINT fk_user_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE addresses
  ADD CONSTRAINT fk_addresses_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE orders
  ADD CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_orders_billing_address_id FOREIGN KEY (billing_address_id) REFERENCES addresses(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_orders_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES addresses(id) ON DELETE SET NULL;

ALTER TABLE order_items
  ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_order_items_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;

ALTER TABLE reservations
  ADD CONSTRAINT fk_reservations_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_reservations_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;

CREATE OR REPLACE VIEW product_list_view AS
SELECT 
  p.id,
  p.product_source,
  p.vendor_article_id,
  p.sku,
  p.ean,
  p.name,
  p.name_en,
  p.name_de,
  p.name_sk,
  p.name_fr,
  p.name_es,
  p.name_ru,
  p.name_it,
  p.name_tr,
  p.name_ro,
  p.name_pl,
  p.description,
  p.description_en,
  p.description_de,
  p.description_sk,
  p.description_fr,
  p.description_es,
  p.description_ru,
  p.description_it,
  p.description_tr,
  p.description_ro,
  p.description_pl,
  p.slug,
  p.base_price,
  p.price,
  p.currency,
  p.stock_quantity,
  p.available_quantity,
  p.reserved_quantity,
  p.reorder_point,
  p.warehouse_location,
  p.is_available,
  p.is_featured,
  p.color,
  p.storage,
  p.ram,
  p.specifications,
  c.id AS category_id,
  c.name AS category_name,
  c.name_en AS category_name_en,
  c.name_de AS category_name_de,
  c.name_sk AS category_name_sk,
  c.name_fr AS category_name_fr,
  c.name_es AS category_name_es,
  c.name_ru AS category_name_ru,
  c.name_it AS category_name_it,
  c.name_tr AS category_name_tr,
  c.name_ro AS category_name_ro,
  c.name_pl AS category_name_pl,
  c.slug AS category_slug,
  b.id AS brand_id,
  b.name AS brand_name,
  b.slug AS brand_slug,
  w.id AS warranty_id,
  w.name AS warranty_name,
  w.duration_months AS warranty_months,
  (SELECT image_url FROM product_images WHERE product_id = p.id AND is_primary = 1 ORDER BY id ASC LIMIT 1) AS primary_image,
  p.last_synced_at,
  p.created_at,
  p.updated_at
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN brands b ON p.brand_id = b.id
LEFT JOIN warranties w ON p.warranty_id = w.id;

COMMIT;
