-- Run this on existing databases to support customer + merchant registration.
ALTER TABLE `users`
  ADD COLUMN `account_type` ENUM('customer', 'merchant') NOT NULL DEFAULT 'customer' AFTER `id`,
  ADD COLUMN `address` VARCHAR(255) NULL AFTER `last_name`,
  ADD COLUMN `postal_code` VARCHAR(20) NULL AFTER `address`,
  ADD COLUMN `city` VARCHAR(100) NULL AFTER `postal_code`,
  ADD COLUMN `country` VARCHAR(100) NULL AFTER `city`,
  ADD COLUMN `mobile` VARCHAR(50) NULL AFTER `phone`,
  ADD COLUMN `tax_number` VARCHAR(100) NULL AFTER `mobile`,
  ADD COLUMN `vat_number` VARCHAR(100) NULL AFTER `tax_number`,
  ADD COLUMN `delivery_address` VARCHAR(255) NULL AFTER `vat_number`,
  ADD COLUMN `delivery_postal_code` VARCHAR(20) NULL AFTER `delivery_address`,
  ADD COLUMN `delivery_city` VARCHAR(100) NULL AFTER `delivery_postal_code`,
  ADD COLUMN `delivery_country` VARCHAR(100) NULL AFTER `delivery_city`,
  ADD COLUMN `account_holder` VARCHAR(200) NULL AFTER `delivery_country`,
  ADD COLUMN `bank_name` VARCHAR(200) NULL AFTER `account_holder`,
  ADD COLUMN `iban` VARCHAR(50) NULL AFTER `bank_name`,
  ADD COLUMN `bic` VARCHAR(30) NULL AFTER `iban`,
  ADD COLUMN `id_card_file` VARCHAR(500) NULL AFTER `bic`,
  ADD COLUMN `passport_file` VARCHAR(500) NULL AFTER `id_card_file`,
  ADD COLUMN `business_registration_certificate_file` VARCHAR(500) NULL AFTER `passport_file`,
  ADD COLUMN `vat_certificate_file` VARCHAR(500) NULL AFTER `business_registration_certificate_file`,
  ADD COLUMN `tax_number_certificate_file` VARCHAR(500) NULL AFTER `vat_certificate_file`,
  ADD INDEX `idx_users_account_type` (`account_type`);
